### ISSUE TITLE
What's the licence on this Project

### ISSUE THREAD

**Issue by AtanGames** [NotHyper-474/Clonecraft#2]
Hi,

What is the licence on the greedy meshing algorithm, am I allowed to use it for a game or use it within the code of an asset store package. I haven't found any licence on the Project this one is based on and there is also no contact information.

Thanks for any answers

**Comment by NotHyper-474** [comment]
Hey, sorry for the silence.

I've now updated this repo with a License. As for the repositories the code is based on, they don't seem to fall under any license, so I consider them to be under The Unlicense.

Best regards.

**Comment by AtanGames** [comment]
Hi, thank you for adding a licence. I appreciate it
